#!/usr/bin/env node

/**
 * Script pour configurer l'accès au réseau local
 * Met à jour automatiquement tous les fichiers de config avec ton IP locale
 * Usage: pnpm setup-network
 */

import { networkInterfaces } from 'os'
import { writeFileSync, readFileSync, existsSync } from 'fs'
import { join } from 'path'

function getLocalIP() {
  const interfaces = networkInterfaces()
  
  // Prioritize WiFi (wlan) interfaces
  for (const [name, addrs] of Object.entries(interfaces)) {
    if (!addrs) continue
    const isWifi = name.toLowerCase().includes('wi-fi') || 
                   name.toLowerCase().includes('wlan') || 
                   name.toLowerCase().includes('wireless')
    if (!isWifi) continue
    for (const addr of addrs) {
      if (addr.family === 'IPv4' && !addr.address.startsWith('127.') && addr.address.startsWith('192.168.')) {
        return addr.address
      }
    }
  }
  
  // Fallback: any non-loopback IPv4 starting with 192.168
  for (const [, addrs] of Object.entries(interfaces)) {
    if (!addrs) continue
    for (const addr of addrs) {
      if (addr.family === 'IPv4' && !addr.address.startsWith('127.') && addr.address.startsWith('192.168.')) {
        return addr.address
      }
    }
  }

  // Last resort: any non-loopback IPv4
  for (const [, addrs] of Object.entries(interfaces)) {
    if (!addrs) continue
    for (const addr of addrs) {
      if (addr.family === 'IPv4' && !addr.address.startsWith('127.')) {
        return addr.address
      }
    }
  }
  
  return 'localhost'
}

function setupNetworkConfig() {
  const localIP = getLocalIP()
  
  // 1. Update apps/web/.env.local
  const envLocalPath = join(process.cwd(), 'apps/web/.env.local')
  const envContent = `# Local Network Configuration
# Auto-generated by: pnpm setup-network
# Run this script again if your IP address changes

VITE_API_URL=http://${localIP}:3001/api/v1
VITE_WS_URL=ws://${localIP}:3001
VITE_STRIPE_PUBLIC_KEY=

# Machine IP: ${localIP}
# To access from another device on the same network, use: http://${localIP}:3000
`
  writeFileSync(envLocalPath, envContent)
  console.log(`✅ apps/web/.env.local updated`)

  // 2. Update capacitor.config.ts LOCAL_IP
  const capacitorConfigPath = join(process.cwd(), 'apps/web/capacitor.config.ts')
  if (existsSync(capacitorConfigPath)) {
    let capacitorContent = readFileSync(capacitorConfigPath, 'utf-8')
    capacitorContent = capacitorContent.replace(
      /const LOCAL_IP = '[^']+'/,
      `const LOCAL_IP = '${localIP}'`
    )
    writeFileSync(capacitorConfigPath, capacitorContent)
    console.log(`✅ apps/web/capacitor.config.ts updated`)
  }

  // 3. Update Android network_security_config.xml
  const networkSecurityPath = join(process.cwd(), 'apps/web/android/app/src/main/res/xml/network_security_config.xml')
  const networkSecurityContent = `<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <!-- Allow cleartext (HTTP) traffic to local network IPs for development -->
    <!-- Auto-generated by: pnpm setup-network (IP: ${localIP}) -->
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">localhost</domain>
        <domain includeSubdomains="true">${localIP}</domain>
    </domain-config>
    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
            <certificates src="system" />
        </trust-anchors>
    </base-config>
</network-security-config>
`
  writeFileSync(networkSecurityPath, networkSecurityContent)
  console.log(`✅ Android network_security_config.xml updated`)

  console.log(``)
  console.log(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`)
  console.log(`📍 Ton IP locale : ${localIP}`)
  console.log(`🌐 Web (navigateur) : http://${localIP}:3000`)
  console.log(`🔌 API : http://${localIP}:3001/health`)
  console.log(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`)
  console.log(``)
  console.log(`Prochaines étapes :`)
  console.log(`  1. Lance : pnpm dev`)
  console.log(`  2. Sur ton téléphone (même WiFi) : http://${localIP}:3000`)
  console.log(`  3. Pour l'app Android, sync : pnpm --filter web exec capacitor sync android`)
  console.log(``)
  console.log(`⚠️  Si l'accès est bloqué, ouvre les ports dans le pare-feu Windows :`)
  console.log(`   Clic droit sur open-ports-admin.ps1 → Exécuter avec PowerShell (en tant qu'administrateur)`)
  console.log(``)
}

setupNetworkConfig()
