ALTER TYPE "EventCategory" ADD VALUE IF NOT EXISTS 'TECH';
ALTER TYPE "EventCategory" ADD VALUE IF NOT EXISTS 'SCIENCE';
ALTER TYPE "EventCategory" ADD VALUE IF NOT EXISTS 'LIFESTYLE';
ALTER TYPE "EventCategory" ADD VALUE IF NOT EXISTS 'TOURISM';
